name: update_site_on_push
on: [push]
env: 
    SECRET: ${{ secrets.SHINYAPPS_SECRET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'
    - name: Install Curl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install R libraries
      run: |
        install.packages(c("rsconnect", "shiny", "dplyr", "ggplot2"))
      shell: Rscript {0}
    - name: Push to site
      run: Rscript bin/upload_to_site.R "$SECRET"