name: update_data
on: [push]

#on:
#  schedule:
#    - cron: "25 4 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'
    - name: Install Curl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install poppler
      run: sudo apt-get install libpoppler-cpp-dev
    - name: Install qpdf
      run: sudo apt-get install qpdf
    - name: Install jpeglib
      run: sudo apt-get install libjpeg-turbo-devel
    - name: Install R libraries
      run: |
        install.packages(c("pdftools", "stringr", "lubridate", "dplyr", "zoo", "qpdf"))
      shell: Rscript {0}
    - name: Run script
      run: Rscript bin/Data_Production_Process.R
    - name: adding new file #this will fail if there's no changes, which is fine, I can clean it up later
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "clehman@manhattan.institute"
        git add -A
        git commit -m "daily update"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
